uktrade/ci-pipeline-config

pingdom-link-checker

link checker first PaaS deployment

Initial conf

---

invest-pir-api.yaml
invest-pir-fe.yaml

Config pulled from develop branch

Invest pir

---

lite-address-service.yaml
lite-case-processing.yaml
lite-company-verification-service.yaml
lite-control-code-service.yaml
lite-country-service.yaml
lite-customer-service.yaml
lite-customs-declaration-service.yaml
lite-exporter-dashboard.yaml
lite-licence-application.yaml
lite-notification-service.yaml
lite-ogel-registration.yaml
lite-ogel-service.yaml
lite-permissions-finder.yaml
lite-permissions-service.yaml
lite-search-management.yaml
lite-spire-relay-service.yaml
lite-user-service.yaml

LITE - remove all Ireland config

---

market-access-api.yaml
market-access.yaml

MA config for London PaaS

---

market-access-api.yaml
market-access.yaml

fix inconsistent naming on MA London

Market access london

---

directory-api.yaml
directory-cms.yaml
directory-companies-house-search.yaml
directory-forms-api.yaml
directory-sso-profile.yaml
directory-sso-proxy.yaml
directory-sso.yaml
directory-ui-buyer.yaml
directory-ui-export-readiness.yaml
directory-ui-supplier.yaml
directory-ui-verification-matching-service-adapter.yaml
directory-ui-verification-provider.yaml
directory-ui-verification.yaml

Directory PaaS London config

---

navigator.yaml

London PaaS config

---

invest-ui_eu-west-2.yaml

migration of invest ui to london

---

market-access-fe.yaml

Start of a new pipeline for django frontend.

Add configuration for market-access-python-frontend

---

legal-basis-api.yaml

- Create YAML configuration file for new `legal-basis-api`
application
I don't know if I should be using another `namespace`, I used `legal-basis` but pretty sure it doesn't exist. Let me know what I should use instead, happy to change it.

Add configuration for legal-basis-api

---

digital-workspace-v2.yaml

Adds configuration for new Django application in `intranet` space

Create configuration for digital-workspace-v2

---

lite-api.yaml
lite-exporter-frontend.yaml
lite-internal-frontend.yaml

Lite new dev

---

dataservices-helpcentre.yaml

new pipeline for data service helpcentre which was previously

---

zenslackchat-staging.yaml

Adding in staging zenslackchat into CI

added zenslackchat staging config

---

zenslackchat.yaml

renamed to just zenslackchat as staging/etc is determined in the file

---

zenslackchat.yaml

Update zenslackchat for stage/prod environments.

Zenslackchat

---

digital-workspace-v2.yaml

new training env

---

data-worspace-prototypes.yaml

adding data workspace prototypes jenkins job

adding data workspace prototypes jenkins job

---

datahub-api-redis-queue-exporter.yaml

Applies the following change:
- Updates the pipeline namespace from `webops` to `datahub` following move.

Update pipeline namespace to datahub.

---

lite-api.yaml
lite-exporter-frontend.yaml
lite-internal-frontend.yaml

Makes the following changes:
- Add pipeline config file for LITE dev2 environment. The following applications:
- api,
- exporter-frontend,
- internal-frontend

Add API and Frontend configuration for LITE dev2 environment.

---

lite-api.yaml
lite-exporter-frontend.yaml
lite-internal-frontend.yaml

Adds pipeline support env for LITE: lite-api-support, lite-exporter-frontend-support, lite-internal-frontend-support.

LITE support environment

---

market-access-api.yaml

Changed dev to gotham.
Added new atlantis environment.
Removed redundant demo and staging environments

TSS-916 - Adding and renaming DMAS environments

---

datasci-data-flow-gscip.yaml

add data-flow-gscip config

---

prototypes-on-paas.yaml

splitting pop between dev and prod environments as per the go-live checklist

Feature - TSS-1391 - Moving POP

---

datasci-data-flow-analysis-group.yaml

The Analysis Group has expressed interest in a folder (so needs the config + other infrastructure)

Adding in a data-flow analysis-group data-flow application

---

public-tariffs-api.yaml

New test environment config added for tariffs-api service.

Update public-tariffs-api.yaml for test env
