uktrade/ci-pipeline-config

directory-api.yaml
The 'dev' environment that this replaces I suspect wasn't doing anything, since
- dev deployments for directory api are currently in Heroku
- The space 'dev-directory' is actually used by
directory-companies-house-search, and this file only concerns
directory-api.git
=> Add feature-branch continual deployment for directory-api

activity-stream-proxy.yaml
We only have the dev environment for pen testing. We don't actually plan to use
this in production: it's a "just in case" project, jfor pen testing now, so we
can quickly use a stand alone endpoint down the line without having to wait+pay
for another round of pen-testing.
=> (feat) Config for activity stream proxy

digital-workspace.yaml, peoplefinder.yaml
Reverts uktrade/ci-pipeline-config#41
@cstutter is moving these env vars into vault, so we're reverting this commit.
=> Revert "Add `APPLICATION_ENV` for People Finder and Workspace"

activity-stream-kibana.yaml
APP_PATH can't be used to specify manifest.yml location, so can't have a repo
that needs different ones, i.e. one for docker and one for buildpack.
=> Kibana in own repo

trade-tariff-reference.yaml
This adds the ci-pipeline configuration for the trade-tariff-reference application.
https://github.com/uktrade/trade-tariff-reference
=> Configuration for trade-tariff-reference application

icms.yaml
Gov PaaS has a bug which doesn't generate requirements.txt file
correctly when there is a private python repo as a separate source.
Which leads to the buildpack try and install all dependencies from
private Viewflow repository and fails.
Also I am not sure how to test this without merging in. Is there a way to do that?
=> Add pre-build to icms to generate requirements.txt

great-cms.yaml
a new environment for great-cms to be used in the UR first and then as beta.great once the new site launches in Q4.
=> creating beta environment for great-cms

lite-exporter-frontend.yaml, lite-internal-frontend.yaml
LITE exporter and internal apps will now be contained in the same repository
with environment variables controlling which interface is shown. The ci-pipline
should pull the code from the same repo for both.
=> Consolidate LITE frontend repos

enquiry-mgmt-tool.yaml
This is specifically to support the Adobe Campaign integration work in the first instance.
=> Add a UAT environment to Enquiry Mgmt Tool

manage-trade-tariffs-design.yaml
Adds a `.yaml` for the prototype application used by the tariff management tool (known as manage-trade-tariffs-design); this app is used internally to demonstrate design ideas.
=> Add configuration for TaMaTo prototype application

data-hub-api-redis-queue-exporter.yaml
Makes the following changes:
- Add a pipeline file for `data-hub-api-redis-queue-exporter` (dev environment)
- Currently set to `webops` space for testing.
Further updates to follow to switch space to datahub, and add further environments.
=> Add pipeline for the data-hub-api Prom RQ exporter

data-hub-api-redis-queue-exporter.yaml
Updates the SCM repo from `data-hub-api.git` (shared) to `prom-rq-exporter.git` (dedicated).
=> Change scm repo to prom-rq-exporter

data-hub-api-redis-queue-exporter.yaml
Applies the following change:
- Updates the app deployment path for the dev environment from `webops-dev` (proving) to `datahub-dev` (dev).
=> Update dev space to datahub-dev.

datahub-api-redis-queue-exporter.yaml
Applies the following change:
- Rename the application names from "data-hub" to "datahub" to match existing apps.
- As above with the pipeline config file.
=> Rename instances of "data-hub" to "datahub"

selling-online-overseas.yaml
This PR updates the name of the `navigator` app to `selling-online-overseas`.
=> Rename navigator app selling-online-overseas

trade-remedies-api.yaml, trade-remedies-caseworker.yaml, trade-remedies-public.yaml
Replacing developer names with generic cities to make it easier to assign and share environments between developers which come and go.
=> Renaming johnny to chicago, chris to tokyo

datasci-data-flow.yaml
The dev-a environment of data-flow no longer exists, and hasn't for a while, so there isn't a need for its config file.
This is being done because we're about to add some more apps to the data-flow setup, so cleaning house a bit first so that setup is as clear as it can be.
=> Remove dev-a environment from data-flow

datasci-data-flow-data-infrastructure.yaml
data-flow is being split into multiple GOV.UK PaaS apps
- One "core" one for the Airflow webserver and Airflow scheduler
- Then one per team of people that write and maintain DAGs that will run Airflow's DAG processor, and run the Airflow tasks themselves.
This is primarily to separate the credentials for the various components, so everything doesn't get access to everything. The webserver and scheduler don't need credentials to access data, and also each team's DAGs don't need access to the credentials for other teams' DAGs.
Since Data Infrastructure is de-facto responsible for all the DAGs, this is the first team chosen to split out, hence the name of this application.
=> Add data-flow-data-infrastructure config

datasci-data-flow-data-science.yaml
This adds a config for a data-flow-data-science app, just like the similar apps data-flow-data-infrastructure and data-flow-gscip.
These are used in data-flow run the dags that a particular team are responsible for, and separated from each other to better isolate credentials.
=> feat: add data-flow-data-science config

datasci-data-flow-opss.yaml
The OPSS are going to be making DAGs to run in data-flow. We now have per-team folders in data-flow that correspond to separate apps in paas for better separation, so it makes sense to make one for the OPSS.
=> feat: add data-flow app for DAGs from the OPSS

datasci-data-flow-tap.yaml
We're separating out some TAP/TaMaTo-specific pipelines in data-flow, so they can be managed separately to other pipelines. This is done via a separate Cloud Foundry application, deployed using this config.
=> feat: add config for data-flow-tap application
